# Generated by Django 3.2.9 on 2021-12-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_user_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
