# Generated by Django 3.2.9 on 2022-01-01 07:54

import account.models
from django.db import migrations, models
import studymate.storage


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211231_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, default='profile_images/cover.jpg', max_length=255, null=True, storage=studymate.storage.OverwriteStorage(), upload_to=account.models.get_cover_image_filepath),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/profile.jpg', max_length=255, null=True, storage=studymate.storage.OverwriteStorage(), upload_to=account.models.get_profile_image_filepath),
        ),
    ]
