# Generated by Django 3.2.9 on 2022-01-05 07:53

import course.models
from django.conf import settings
from django.db import migrations, models
import studymate.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('profile_image', models.ImageField(blank=True, default='banner/banner.jpg', max_length=255, null=True, storage=studymate.storage.OverwriteStorage(), upload_to=course.models.get_course_banner_filepath)),
                ('ratings', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('course', models.ManyToManyField(related_name='user', to='course.Course')),
                ('user', models.ManyToManyField(related_name='course', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
