# Generated by Django 3.2.9 on 2022-01-05 15:19

import course.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import studymate.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(default='banner/banner.jpg', max_length=255, storage=studymate.storage.OverwriteStorage(), upload_to=course.models.get_course_banner_filepath)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='ratings',
            new_name='overall_ratings',
        ),
        migrations.RenameField(
            model_name='usercourse',
            old_name='progress',
            new_name='course_progress',
        ),
        migrations.RemoveField(
            model_name='course',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='course',
            name='banner_image',
            field=models.ImageField(default='banner/banner.jpg', max_length=255, storage=studymate.storage.OverwriteStorage(), upload_to=course.models.get_course_banner_filepath),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='complete_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='course',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='course.course'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='user',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='account.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CourseUserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_content_group', models.PositiveIntegerField(default=1)),
                ('last_content', models.PositiveIntegerField(default=1)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='course.usercourse')),
            ],
        ),
        migrations.CreateModel(
            name='CourseContentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_group', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('is_video', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='course.coursecontentgroup')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(related_name='courses', to='course.CourseCategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='course', to='course.CourseInstructor'),
        ),
    ]
