# Generated by Django 3.2.9 on 2022-01-06 16:25

import course.models
from django.db import migrations, models
import studymate.storage


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220105_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='course',
            name='banner_image',
            field=models.ImageField(default='course/banner/banner.jpg', max_length=255, storage=studymate.storage.OverwriteStorage(), upload_to=course.models.get_course_banner_filepath),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='profile_image',
            field=models.ImageField(default='profile_images/profile.jpg', max_length=255, storage=studymate.storage.OverwriteStorage(), upload_to=course.models.get_course_instructor_filepath),
        ),
    ]
