# Generated by Django 3.2.9 on 2022-01-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20220106_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='video_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
