# Generated by Django 3.2.9 on 2022-01-07 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0005_coursecontent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_made_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
