# Generated by Django 3.2.9 on 2022-01-07 13:14

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_maker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
