# Generated by Django 3.2.9 on 2022-01-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_coursecontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
