# Generated by Django 3.2.9 on 2021-12-30 09:54

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_agenda_musiclinks_relaxsettings_relaxtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaxsettings',
            name='link_image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='relaxsettings',
            name='local_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=dashboard.models.get_bg_filepath),
        ),
        migrations.AddField(
            model_name='relaxsettings',
            name='use_default_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relaxsettings',
            name='use_default_music',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relaxsettings',
            name='use_default_text',
            field=models.BooleanField(default=True),
        ),
    ]
