# Generated by Django 3.2.9 on 2021-12-31 16:12

import dashboard.models
from django.db import migrations, models
import studymate.storage


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211230_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='profile_image',
            field=models.ImageField(blank=True, default='banner/banner.png', max_length=255, null=True, storage=studymate.storage.OverwriteStorage(), upload_to=dashboard.models.get_course_banner_filepath),
        ),
        migrations.AlterField(
            model_name='relaxsettings',
            name='local_image',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=studymate.storage.OverwriteStorage(), upload_to=dashboard.models.get_bg_filepath),
        ),
    ]
