# Generated by Django 3.2.9 on 2022-01-01 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notes',
            name='overall_rating',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='NotesRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='notes.notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
