# Generated by Django 3.2.9 on 2022-01-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20220101_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='category',
        ),
        migrations.AddField(
            model_name='notes',
            name='category',
            field=models.ManyToManyField(related_name='notes', to='notes.NotesCategory'),
        ),
    ]
