# Generated by Django 3.2.9 on 2022-01-02 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notes.models
import studymate.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0005_alter_notescategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesrating',
            name='comment',
        ),
        migrations.AlterField(
            model_name='notes',
            name='thumbnail',
            field=models.ImageField(default='notes/thumbnail.jpg', storage=studymate.storage.OverwriteStorage, upload_to=notes.models.get_note_thumbnail_filepath),
        ),
        migrations.CreateModel(
            name='NotesDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='notes.notes')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_parent', to='notes.notesdiscussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_discussion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
