# Generated by Django 3.2.9 on 2022-01-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20220102_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesrating',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
