# Generated by Django 3.2.9 on 2022-01-03 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0009_auto_20220103_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesratingvotes',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_votes', to='account.user'),
        ),
    ]
