# Generated by Django 3.2.9 on 2022-01-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_alter_notesratingvotes_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesrating',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
