# Generated by Django 3.2.9 on 2022-01-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_notesrating_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesrating',
            name='votes_total',
            field=models.IntegerField(default=0),
        ),
    ]
