# Generated by Django 3.2.9 on 2022-01-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_notesrating_votes_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesrating',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
